### ISSUE TITLE
Some error labels in the coco-inpainted dataset

### ISSUE THREAD

**Issue by sukirk** [ragavsachdeva/CYWS-3D#9]
I found some error labels generated from `InpatinedCocoDataset`, such as `InpatinedCocoDataset('D:/Dataset/coco-inpainted/test/large', 'test', 'centernet', 'affine')`. 
I visualize some examples of `_0.jpg` below.
<img width="264" alt="image" src="https://github.com/user-attachments/assets/295d4c94-dd3e-4ded-bd45-6efc96a70f4e">
where
- (a) is correct. 
- The bounding box of (b) is strange. 
- The bounding box of (c) is located in the bottom right corner, far smaller than the definition of *large*.

I also noticed some data generated from `InpatinedCocoDataset` is `None`, thus I need to skip this void sample. Is my findings correct? These errors may limit the accuracy.

**Comment by ragavsachdeva** [comment]
Hi, sorry for the delayed response. I don't actively monitor this repo anymore.

- (a) is indeed correct, as you've pointed out
- For (b) consider the computer screen box. It helps to think of it as "what would be corresponding regions in the two images, if the screen didn't disappear?" So the box is only in the lower half of the screen because the top half of the screen isn't/wouldn't be visible in the right image. In other words, for all we know the top half of the screen is still there in the scene on the right, just out of view.
- For (c) I believe the geometric augmentation is to be blamed. The object in the original image must've been "large".

I really don't remember I'm afraid. It's always safe to skip None haha.
